{% set name = "fegrow" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cole-group/FEgrow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee5c526a8c6984b79cbddb6f81779e0eea3942241c12fce19d906bdc63d52e9b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.11
    - notebook <7.0.0
    - openmmforcefields >=0.9.0
    - openbabel
    - rdkit
    - mols2grid >=0.2.4
    - openff-toolkit >=0.13
    - parmed
    - openmm >=7.5.0
    - openmm-ml
    - typing-extensions
    - pdbfixer >=1.8.0
    - tqdm
    - torchani >2.2.0
    - openmm-torch >=0.8
    - pytorch >=1.10.0
    - py3dmol >=1.8.0
    - prody >=2.0.2
    - pint !=0.2
    - networkx
    - pint-pandas
    - dask
    - modAL
    - cachey
    - pyparsing <3.1.0

test:
  imports:
    - fegrow
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -c "import pytest; from fegrow.testing import loc ; pytest.main([loc])"

about:
  home: https://cole-group.github.io/FEgrow/
  summary: 'FEgrow: generate congeneric ligands for FEP by growing a template molecule.'
  description: |
    FEgrow is an interactive workflow for building user-defined 
    congeneric series of ligands in protein binding pockets 
    for input to free energy calculations. 
    Furthermore, FEgrow was extended in 2.0.0 to support Active Learning
    and scaling with Dask. 
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://cole-group.github.io/FEgrow/
  dev_url: https://github.com/cole-group/FEgrow

extra:
  recipe-maintainers:
    - bieniekmateusz
